# ============================================================
# no-SpO2 rerun shell copy generated by prepare_no_spo2_patch_base_no_weightedensemble_V2.py
# Uses run_data4_three_outcomes_with_shap_no_weightedensemble.py as base script.
# Original shell script: run_data10_overall_top10_shap_youden.sh
# ============================================================

#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/Users/yan_1nvincible/Documents/muhong 机器学习"
PYTHON_BIN="/Users/yan_1nvincible/ag_env/bin/python"

DATA_FILE="${PROJECT_DIR}/data10_no_spo2.xlsx"
OUTDIR="${PROJECT_DIR}/autogluon_data10_total_top10_shap_youden_no_spo2"

MAIN_SCRIPT="${PROJECT_DIR}/run_data4_overall_with_shap_forced_pdp.py"
RECALC_SCRIPT="${PROJECT_DIR}/recalculate_overall_optimal_thresholds_fixed_bp.py"

LOG_FILE="${PROJECT_DIR}/data10_total_top10_shap_youden.log"

cd "${PROJECT_DIR}"

echo "============================================================" | tee "${LOG_FILE}"
echo "Running data10 overall analysis with top 10 SHAP and Youden threshold" | tee -a "${LOG_FILE}"
echo "Project dir: ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
echo "Data file: ${DATA_FILE}" | tee -a "${LOG_FILE}"
echo "Output dir: ${OUTDIR}" | tee -a "${LOG_FILE}"
echo "Python: ${PYTHON_BIN}" | tee -a "${LOG_FILE}"
echo "Started at: $(date)" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"

if [ ! -f "${DATA_FILE}" ]; then
  echo "ERROR: data file not found: ${DATA_FILE}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${MAIN_SCRIPT}" ]; then
  echo "ERROR: main script not found: ${MAIN_SCRIPT}" | tee -a "${LOG_FILE}"
  echo "Please put run_data4_overall_with_shap_forced_pdp.py in ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${RECALC_SCRIPT}" ]; then
  echo "ERROR: recalculation script not found: ${RECALC_SCRIPT}" | tee -a "${LOG_FILE}"
  echo "Please put recalculate_overall_optimal_thresholds_fixed_bp.py in ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -x "${PYTHON_BIN}" ]; then
  echo "ERROR: Python not found or not executable: ${PYTHON_BIN}" | tee -a "${LOG_FILE}"
  echo "Please check your ag_env path." | tee -a "${LOG_FILE}"
  exit 1
fi

echo "" | tee -a "${LOG_FILE}"
echo "Step 0: Clean Ray leftovers" | tee -a "${LOG_FILE}"
pkill -f ray || true
rm -rf /tmp/ray || true

echo "" | tee -a "${LOG_FILE}"
echo "Step 1: Run overall AutoGluon pipeline with top 10 SHAP and forced PDP" | tee -a "${LOG_FILE}"

"${PYTHON_BIN}" -u "${MAIN_SCRIPT}" \
  --file "${DATA_FILE}" \
  --base-script "${PROJECT_DIR}/run_data4_three_outcomes_with_shap_no_weightedensemble.py" \
  --outdir "${OUTDIR}" \
  --num-cpus 2 \
  --shap-background 60 \
  --shap-explain 120 \
  --shap-nsamples 30 \
  --shap-top-n 10 \
  --pdp-top-n 5 \
  2>&1 | tee -a "${LOG_FILE}"

echo "" | tee -a "${LOG_FILE}"
echo "Step 2: Recalculate optimal-threshold metrics using Youden index" | tee -a "${LOG_FILE}"

"${PYTHON_BIN}" -u "${RECALC_SCRIPT}" \
  --parent-dir "${PROJECT_DIR}" \
  --data-file "${DATA_FILE}" \
  --overall-dir "${OUTDIR}" \
  --threshold-method youden \
  2>&1 | tee -a "${LOG_FILE}"

echo "" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo "All done." | tee -a "${LOG_FILE}"
echo "Results saved to: ${OUTDIR}" | tee -a "${LOG_FILE}"
echo "Log saved to: ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "Finished at: $(date)" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
