# ============================================================
# no-SpO2 rerun shell copy generated by prepare_no_spo2_patch_base_no_weightedensemble_V2.py
# Uses run_data4_three_outcomes_with_shap_no_weightedensemble.py as base script.
# Original shell script: run_data10_old_young_top10_shap_youden.sh
# ============================================================

#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/Users/yan_1nvincible/Documents/muhong 机器学习"
PYTHON_BIN="/Users/yan_1nvincible/ag_env/bin/python"

OLD_FILE="${PROJECT_DIR}/data10-old_no_spo2.xlsx"
YOUNG_FILE="${PROJECT_DIR}/data10-young_no_spo2.xlsx"

OUTDIR="${PROJECT_DIR}/autogluon_data10_old_young_top10_shap_youden_no_spo2"

# 这个脚本是之前 old/young 年龄亚组完整机器学习流程脚本
ML_SCRIPT="${PROJECT_DIR}/run_data4_old_young_subgroups_optimal_threshold.py"

# 这个脚本是之前 old/young 亚组 SHAP 解释脚本
SHAP_SCRIPT="${PROJECT_DIR}/run_shap_old_young_subgroups.py"

LOG_FILE="${PROJECT_DIR}/data10_old_young_top10_shap_youden.log"

cd "${PROJECT_DIR}"

echo "============================================================" | tee "${LOG_FILE}"
echo "Running data10 old/young subgroup analysis with Youden threshold and top 10 SHAP" | tee -a "${LOG_FILE}"
echo "Project dir: ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
echo "Old file: ${OLD_FILE}" | tee -a "${LOG_FILE}"
echo "Young file: ${YOUNG_FILE}" | tee -a "${LOG_FILE}"
echo "Output dir: ${OUTDIR}" | tee -a "${LOG_FILE}"
echo "Python: ${PYTHON_BIN}" | tee -a "${LOG_FILE}"
echo "Started at: $(date)" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"

if [ ! -x "${PYTHON_BIN}" ]; then
  echo "ERROR: Python not found or not executable: ${PYTHON_BIN}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${OLD_FILE}" ]; then
  echo "ERROR: old data file not found: ${OLD_FILE}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${YOUNG_FILE}" ]; then
  echo "ERROR: young data file not found: ${YOUNG_FILE}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${ML_SCRIPT}" ]; then
  echo "ERROR: ML script not found: ${ML_SCRIPT}" | tee -a "${LOG_FILE}"
  echo "Please put run_data4_old_young_subgroups_optimal_threshold.py into ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
  exit 1
fi

echo "" | tee -a "${LOG_FILE}"
echo "Step 0: Clean Ray leftovers" | tee -a "${LOG_FILE}"
pkill -f ray || true
rm -rf /tmp/ray || true

echo "" | tee -a "${LOG_FILE}"
echo "Step 1: Run old/young AutoGluon subgroup analysis with Youden threshold" | tee -a "${LOG_FILE}"

"${PYTHON_BIN}" -u "${ML_SCRIPT}" \
  --file1 "${OLD_FILE}" \
  --file2 "${YOUNG_FILE}" \
  --name1 "old" \
  --name2 "young" \
  --outdir "${OUTDIR}" \
  --num-cpus 2 \
  --threshold-method youden \
  2>&1 | tee -a "${LOG_FILE}"

echo "" | tee -a "${LOG_FILE}"
echo "Step 2: Run SHAP top 10 for old/young subgroups" | tee -a "${LOG_FILE}"

if [ -f "${SHAP_SCRIPT}" ]; then
  "${PYTHON_BIN}" -u "${SHAP_SCRIPT}" \
    --old-file "${OLD_FILE}" \
    --young-file "${YOUNG_FILE}" \
    --result-dir "${OUTDIR}" \
    --n-background 60 \
    --n-explain 120 \
    --nsamples 30 \
    --top-n 10 \
    2>&1 | tee -a "${LOG_FILE}"
else
  echo "WARNING: SHAP script not found: ${SHAP_SCRIPT}" | tee -a "${LOG_FILE}"
  echo "The ML analysis is complete, but SHAP was skipped." | tee -a "${LOG_FILE}"
fi

echo "" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo "All done." | tee -a "${LOG_FILE}"
echo "Results saved to: ${OUTDIR}" | tee -a "${LOG_FILE}"
echo "Log saved to: ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "Finished at: $(date)" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
