# ============================================================
# no-SpO2 rerun shell copy generated by prepare_no_spo2_patch_base_no_weightedensemble_V2.py
# Uses run_data4_three_outcomes_with_shap_no_weightedensemble.py as base script.
# Original shell script: run_data10_sub4_sub4minus_top10_shap_youden.sh
# ============================================================

#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/Users/yan_1nvincible/Documents/muhong 机器学习"
PYTHON_BIN="/Users/yan_1nvincible/ag_env/bin/python"

SUB4_FILE="${PROJECT_DIR}/data10-sub4_no_spo2.xlsx"
SUB4_MINUS_FILE="${PROJECT_DIR}/data10-sub4-_no_spo2.xlsx"

OUTDIR="${PROJECT_DIR}/autogluon_data10_sub4_sub4minus_top10_shap_youden_no_spo2"

ML_SCRIPT="${PROJECT_DIR}/run_data4_old_young_subgroups_optimal_threshold.py"
SHAP_SCRIPT="${PROJECT_DIR}/run_shap_two_subgroups.py"

LOG_FILE="${PROJECT_DIR}/data10_sub4_sub4minus_top10_shap_youden.log"

cd "${PROJECT_DIR}"

echo "============================================================" | tee "${LOG_FILE}"
echo "Running data10 sub4/sub4- subgroup analysis with Youden threshold and top 10 SHAP" | tee -a "${LOG_FILE}"
echo "Project dir: ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
echo "sub4 file: ${SUB4_FILE}" | tee -a "${LOG_FILE}"
echo "sub4_minus file: ${SUB4_MINUS_FILE}" | tee -a "${LOG_FILE}"
echo "Output dir: ${OUTDIR}" | tee -a "${LOG_FILE}"
echo "Python: ${PYTHON_BIN}" | tee -a "${LOG_FILE}"
echo "Started at: $(date)" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"

if [ ! -x "${PYTHON_BIN}" ]; then
  echo "ERROR: Python not found or not executable: ${PYTHON_BIN}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${SUB4_FILE}" ]; then
  echo "ERROR: sub4 data file not found: ${SUB4_FILE}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${SUB4_MINUS_FILE}" ]; then
  echo "ERROR: sub4_minus data file not found: ${SUB4_MINUS_FILE}" | tee -a "${LOG_FILE}"
  exit 1
fi

if [ ! -f "${ML_SCRIPT}" ]; then
  echo "ERROR: ML script not found: ${ML_SCRIPT}" | tee -a "${LOG_FILE}"
  echo "Please put run_data4_old_young_subgroups_optimal_threshold.py into ${PROJECT_DIR}" | tee -a "${LOG_FILE}"
  exit 1
fi

echo "" | tee -a "${LOG_FILE}"
echo "Step 0: Clean Ray leftovers" | tee -a "${LOG_FILE}"
pkill -f ray || true
rm -rf /tmp/ray || true

echo "" | tee -a "${LOG_FILE}"
echo "Step 1: Run sub4/sub4_minus AutoGluon subgroup analysis with Youden threshold" | tee -a "${LOG_FILE}"

"${PYTHON_BIN}" -u "${ML_SCRIPT}" \
  --file1 "${SUB4_FILE}" \
  --file2 "${SUB4_MINUS_FILE}" \
  --name1 "sub4" \
  --name2 "sub4_minus" \
  --outdir "${OUTDIR}" \
  --num-cpus 2 \
  --threshold-method youden \
  2>&1 | tee -a "${LOG_FILE}"

echo "" | tee -a "${LOG_FILE}"
echo "Step 2: Run SHAP top 10 for sub4/sub4_minus subgroups" | tee -a "${LOG_FILE}"

if [ -f "${SHAP_SCRIPT}" ]; then
  "${PYTHON_BIN}" -u "${SHAP_SCRIPT}" \
    --group1-name "sub4" \
    --group1-file "${SUB4_FILE}" \
    --group2-name "sub4_minus" \
    --group2-file "${SUB4_MINUS_FILE}" \
    --result-dir "${OUTDIR}" \
    --n-background 60 \
    --n-explain 120 \
    --nsamples 30 \
    --top-n 10 \
    2>&1 | tee -a "${LOG_FILE}"
else
  echo "WARNING: SHAP script not found: ${SHAP_SCRIPT}" | tee -a "${LOG_FILE}"
  echo "The ML analysis is complete, but SHAP was skipped." | tee -a "${LOG_FILE}"
fi

echo "" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo "All done." | tee -a "${LOG_FILE}"
echo "Results saved to: ${OUTDIR}" | tee -a "${LOG_FILE}"
echo "Log saved to: ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "Finished at: $(date)" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
